services:
  - type: web
    name: ebook-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
